### ISSUE TITLE
Query parameters

### ISSUE THREAD

**Issue by G3z** [log0ymxm/node-harvest#34]
There are a couple of issues ( https://github.com/log0ymxm/node-harvest/issues/25 , https://github.com/log0ymxm/node-harvest/issues/11 ) and PR ( https://github.com/log0ymxm/node-harvest/pull/33 , https://github.com/log0ymxm/node-harvest/pull/30 )  related to query parameters 
I'm working on a [branch](https://github.com/log0ymxm/node-harvest/tree/query_parameters) to add the functionality once and for all.

i've added a couple of tests and things seems to be working well.

Any comment/help is appreciated

**Comment by log0ymxm** [comment]
I initially implemented this library to get some basic functionality with the harvest API, and since at the time there was no full node.js clients I stubbed out all the endpoints and a really basic set of tests. 

So one of the things that never really got fully implemented were the query parameters, and as you've mentioned they've kind of been ad-hoc implemented by individual contributions. This is needed, I'll see if I can take a look at your work and offer some help. But definitely +1.
